//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myinnovation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student1
    {
        public int Id { get; set; }
        public string StudentName { get; set; }
        public int Subject_Id { get; set; }
        public int Teacher_Id { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual Teacher Teacher { get; set; }
        public  IEnumerable<Student1> StudList { get; set; }
    }
}
